### ISSUE TITLE
Instructor Feedback - Week 10

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [manderson394/covidPulse#3]
@kkelm @En-8  @manderson394 While this certainly isn't a service I ever would have anticipated being built at the start of the semester; it's very relevant choice now!  You've done a good job defining the problem and solution and documenting your time log/journal. Keep up that good work!

- [x] Endpoints (resources/operations) make good sense; I particularly like the idea of being able to see data for a date range (I'm assuming that will show the counts per day). Question: what response types will be supported (or did I overlook this?) I am assuming json as you have output samples of that...  Any thoughts about plaintext, xml, html?  Maybe even sending back an already-built chart!?  
- [x] Project plan?

**Comment by kkelm** [comment]
Right now we're thinking of just producing JSON, so the user can manipulate the data however they choose. As for the project plan, we should have one soon.
